import { DFTemplate } from '../o-dynamic-form.template';
// import { TextField } from './textfield/textfield';
// import { ButtonField } from './button/button';
// import { ColumnsField } from './columns/columns';
// import { ContainerField } from './container/container';
// import { EmailField } from './email/email';
// import { CheckBoxField } from './checkbox/checkbox';
// import { DataGrid } from './datagrid/datagrid';
// import { TextAreaField } from './textarea/textarea';
// import { PasswordField } from './password/password';
// import { NumberField } from './number/number';
// import { HiddenField } from './hidden/hidden';
// import { RadioField } from './radio/radio';
// import { CustomField } from './custom/custom';
// import { TableField } from './table/table';
// import { PanelField } from './panel/panel';
// import { FieldSetField } from './fieldset/fieldset';
// import { WellField } from './well/well';
// import { DateTimeField } from './datetime/datetime';
// import { CurrencyField } from './currency/currency';
// import { SelectBoxField } from './selectboxes/selectboxes';
// import { ContentField } from './content/content';
// import { HtmlField } from './html/html';
// import { SelectField } from './select/select';
// import { SurveyField } from './survey/survey';
// import { ResourceField } from './resource/resource';
// import { AddressField } from './address/address';
// import { PhoneNumberField } from './phonenumber/phonenumber';
// import { SignatureField } from './signature/signature';
// import { DayField } from './day/day';

import { OCurrencyInput } from './input/currency-input/o-currency-input';
import { ODateInput } from './input/date-input/o-date-input';
import { OEmailInput } from './input/email-input/o-email-input';
import { OIntegerInput } from './input/integer-input/o-integer-input';
import { ONifInput } from './input/nif-input/o-nif-input';
import { OPasswordInput } from './input/password-input/o-password-input';
import { OPercentInput } from './input/percent-input/o-percent-input';
import { ORealInput } from './input/real-input/o-real-input';
import { OTextInput } from './input/text-input/o-text-input';
import { OTextareaInput } from './input/textarea-input/o-textarea-input';

import { OColumn } from './container/o-column';
import { ORow } from './container/o-row';


export function RegisterComponents(template: DFTemplate) {
    OCurrencyInput(template);
    ODateInput(template);
    OEmailInput(template);
    OIntegerInput(template);
    ONifInput(template);
    OPasswordInput(template);
    OPercentInput(template);
    ORealInput(template);
    OTextInput(template);
    OTextareaInput(template);

    OColumn(template);
    ORow(template);
    // ButtonField(template);
    // ColumnsField(template);
    // ContainerField(template);
    // DataGrid(template);
    // EmailField(template);
    // TextAreaField(template);
    // HiddenField(template);
    // PasswordField(template);
    // NumberField(template);
    // RadioField(template);
    // CheckBoxField(template);
    // CustomField(template);
    // TableField(template);
    // PanelField(template);
    // FieldSetField(template);
    // WellField(template);
    // DateTimeField(template);
    // CurrencyField(template);
    // SelectBoxField(template);
    // ContentField(template);
    // HtmlField(template);
    // SelectField(template);
    // SurveyField(template);
    // ResourceField(template);
    // AddressField(template);
    // PhoneNumberField(template);
    // SignatureField(template);
    // DayField(template);
}
